mobie/mobie-viewer-fiji

- src/main/java/de/embl/cba/mobie/image/ImagePropertiesToMetadataAdapter.java
- src/main/java/de/embl/cba/mobie/image/MutableImageProperties.java
- src/main/java/de/embl/cba/mobie/ui/viewer/SourcesPanel.java
Add valueLimits to bookmarks. 
This now means that 'contrastLimits' is used for the brightness of the segmentation, and 'valueLimits' for the specific limits for colorByColumn. If no valueLimits are supplied, it uses the min/max of the specified column (same as default for colouring by column from the table menu)
For issue: https://github.com/mobie/mobie-viewer-fiji/issues/127
> add valueLimits to bookmarks

- src/main/java/de/embl/cba/mobie/bookmark/BookmarkGithubWriter.java
- src/main/java/de/embl/cba/mobie/bookmark/BookmarksJsonParser.java
- src/main/java/de/embl/cba/mobie/bookmark/BookmarksManager.java
- src/main/java/de/embl/cba/mobie/image/ImagePropertiesToMetadataAdapter.java
- src/main/java/de/embl/cba/mobie/image/SourcesModel.java
- src/main/java/de/embl/cba/mobie/ui/viewer/ActionPanel.java
- src/main/java/de/embl/cba/mobie/ui/viewer/MoBIEViewer.java
- src/main/java/de/embl/cba/mobie/ui/viewer/SourcesDisplayUI.java
- src/main/java/de/embl/cba/mobie/ui/viewer/SourcesPanel.java
Main changes:
- Only bookmarks in default.json are loaded by default
- Other bookmarks are loaded via the context menu 'load additional bookmarks..' and follows the same logic (and uses most of the same code) as loading additional tables. i.e. can select from file on project or file system
- Bookmarks can be saved via the context menu 'save current settings as bookmark..' with similar logic to above. i.e. can select to save to project or to file system. For saving to a project on github, at the moment this works the same as PlateViewer, and requires an access token with push access to the repo. For saving to project or file system, if you select a file that already exists, it will append to that file. (appending to json files is actually a pain, so really it parses the file, appends the …
> Bookmark ui

- src/main/java/de/embl/cba/mobie/image/ImagePropertiesToMetadataAdapter.java
- src/main/java/de/embl/cba/mobie/image/MutableImageProperties.java
I added the 3d resolution to the metadata / imageproperties. 
I will need to add a bit to the function here: https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/bookmark/BookmarksManager.java#L170 when you're done. It needs a getter for the current resolution 3d value. This is so the current value can be written to a bookmark, if it has been changed via the context menu.
> add resolution 3d

- src/main/java/de/embl/cba/mobie/n5/N5S3ImageLoader.java
- src/main/java/de/embl/cba/mobie/n5/XmlIoN5S3ImageLoader.java
- src/main/java/de/embl/cba/mobie/n5/XmlIoN5S3ZarrImageLoader.java
- src/main/java/de/embl/cba/mobie/n5/zarr/N5S3OMEZarrImageLoader.java
- src/main/java/de/embl/cba/mobie/n5/zarr/OMEZarrS3Reader.java
- can read from private s3 buckets now
- got rid of the s3 authentication mode; so `Authentication` is not necessary in the `bdv.n5.xml` any more (cc @K-Meech)
Needs https://github.com/tischi/imagej-utils/pull/46
> Remove s3 authentication code in favor of dynamic credentials

- src/main/java/de/embl/cba/mobie/n5/zarr/OMEZarrReader.java
- src/main/java/de/embl/cba/mobie/n5/zarr/ui/OpenOMEZARRCommand.java
Viewer plugin update that allows opening ome.zarr from the filesystem through the menu item in Fiji:
"Plugins>BigDataViewer>OME ZARR>Open OME ZARR from the file system..."
> Enable opening ome.zarr from the filesystem

- src/main/java/de/embl/cba/mobie/bdv/ViewerTransformLogger.java
- src/main/java/de/embl/cba/mobie/view/ViewerManager.java
I found a couple of other places where we were still using ```Utils.getMousePosition()```. 
I think using the window centre for all the viewer transform stuff is more consistent.
> use window centre for normalised affine

- src/main/java/de/embl/cba/mobie/color/ColoringModelHelper.java
Fixes https://github.com/mobie/mobie-viewer-fiji/issues/264
Fixes errors when loading bookmarks that 'color by column' with a categorical lut. These don't need a min/max value limit in the view.
> fix platynereis bookmark issues

- src/main/java/de/embl/cba/mobie/Utils.java
- src/main/java/de/embl/cba/mobie/projectcreator/ui/ProjectsCreatorPanel.java
- src/main/java/de/embl/cba/mobie/table/TableViewer.java
- src/main/java/de/embl/cba/mobie/view/additionalviews/AdditionalViewsLoader.java
- src/main/java/de/embl/cba/mobie/view/saving/ViewsSaver.java
Fixes https://github.com/mobie/mobie-viewer-fiji/issues/340
Makes all jfilechoosers remember the last selected directory on the filesystem e.g. when:
- saving additional views
- loading additional views
- loading additional tables
> remember last selected dir

- src/main/java/de/embl/cba/mobie/MoBIE.java
- src/main/java/de/embl/cba/mobie/Utils.java
- src/main/java/de/embl/cba/mobie/n5/zarr/N5OMEZarrImageLoader.java
- src/main/java/de/embl/cba/mobie/n5/zarr/OMEZarrReader.java
- src/main/java/de/embl/cba/mobie/transform/GridSourceTransformer.java
- src/main/java/de/embl/cba/mobie/view/ViewManager.java
Hi @KateMoreva (cc @K-Meech),
I hacked in a `SharedQueue` for OMEZarr. This helps in terms of not creating too many threads when adding very many Sources to BDV.
I would like to merge this as it will enable @constantinpape to have a look at the plate view images.
But it would be good if you could take note of what I did here such that we can make a nice implementation of this in bdv-imageloader.
> Implement shared queue for OMEZarr

- src/main/java/de/embl/cba/mobie/display/AnnotatedIntervalDisplay.java
- src/main/java/de/embl/cba/mobie/display/ImageSourceDisplay.java
- src/main/java/de/embl/cba/mobie/display/SegmentationSourceDisplay.java
Fixes https://github.com/mobie/mobie-viewer-fiji/issues/397
@tischi Ok! So it turns out, that if you don't have a default/empty constructor then gson.fromJson() sets any missing fields to their default values. i.e. null for objects, false for booleans etc.. It won't use the values you state as field=value.
I fixed this for the displays, but if there's anywhere else you rely on default values, you will need to add a constructor!
> add default constructor

- src/main/java/de/embl/cba/mobie/bdv/render/AccumulateOccludingProjectorARGBFactory.java
- src/main/java/de/embl/cba/mobie/bdv/render/AccumulateOccludingProjectorARGBFactoryAdapter.java
- src/main/java/de/embl/cba/mobie/bdv/render/BlendingMode.java
Turns javadoc comments with errors into normal multi-line comments.
> fix javadoc errors

- src/main/java/org/embl/mobie/viewer/MoBIE.java
Closes https://github.com/mobie/mobie-viewer-fiji/issues/465
@tischi I removed the extra wrapping as a transformed source. I checked that we could still manually move sources and save/load a view. All worked fine :)
> remove extra wrap

- src/main/java/org/embl/mobie/viewer/annotate/Annotator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java
- src/main/java/org/embl/mobie/viewer/ui/MoBIELookAndFeelToggler.java
- src/main/java/org/embl/mobie/viewer/ui/UserInterface.java
- src/main/java/org/embl/mobie/viewer/ui/UserInterfaceHelper.java
- src/main/java/org/embl/mobie/viewer/view/ViewManager.java
- src/main/java/org/embl/mobie/viewer/view/additionalviews/AdditionalViewsLoader.java
- src/main/java/org/embl/mobie/viewer/view/saving/SelectExistingViewFrame.java
For https://github.com/mobie/mobie-viewer-fiji/issues/468
- stores the laf when mobie is opened, and resets to this
- sets no laf for the project creator, so the default is used
This means menus/dialogs before and after using mobie now look the same on Windows (and hopefully on all other os!)
Project creator on windows:
@tischi - does this look alright on mac too?
> Project creator laf

- src/main/java/org/embl/mobie/viewer/ui/UserInterfaceHelper.java
Closes https://github.com/mobie/mobie-viewer-fiji/issues/470
- checks if a view is already present in a particular group dropdown. This stops 'loading additional views..' with views of the same name leading to multiple entries in the dropdown. Newly loaded views replace old ones.
> Replace views of the same name

- src/main/java/org/embl/mobie/viewer/Utils.java
- src/main/java/org/embl/mobie/viewer/view/ViewManager.java
For https://github.com/mobie/mobie-viewer-fiji/issues/471
When a sourceDisplay is removed, it also removes any sourceTransformers that no longer apply to any displayed sources. (prevents old sourceTransformers being saved into views)
> remove sourceTransformers that apply to non-displayed sources

- src/main/java/org/embl/mobie/viewer/command/WriteOMEZARRCommand.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ImagesCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ManualExportPanel.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java
- src/test/java/org/embl/mobie/viewer/projectcreator/ImagesCreatorTest.java
- src/test/java/org/embl/mobie/viewer/projectcreator/RemoteMetadataCreatorTest.java
Fixes https://github.com/mobie/mobie-viewer-fiji/issues/589
Main changes:
- allows images to be overwritten in the project creator
- separates the last of the project creator ui from the actual api (e.g. manual export) for https://github.com/mobie/mobie-viewer-fiji/issues/591
- allows changing the name of bdv format images when added to project
- fixes bug with linking to bdv format images
> Overwrite images

- src/main/java/org/embl/mobie/viewer/projectcreator/DatasetJsonCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ImagesCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ProjectCreatorHelper.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java
Fixes https://github.com/mobie/mobie-viewer-fiji/issues/590 and https://github.com/mobie/mobie-viewer-fiji/issues/579
Main changes:
- Splits affine transform in ui into 3 rows
- Adds this affine to the view, not directly to the xml. Now the xml will always contain the scaling from the image itself (from imp.getCalibration()), and this affine will be added to the view on top.
> Add project creator affine to view, not xml

- pom.xml
- src/main/java/org/embl/mobie/viewer/projectcreator/RemoteMetadataCreator.java
for https://github.com/mobie/mobie-viewer-fiji/issues/615
This removes the 'data' folder from the s3 address for OME-ZARR written by the project creator
@tischi - I think this should fix your issue
> remove data folder from s3address

- pom.xml
- src/main/java/org/embl/mobie/viewer/projectcreator/ImagesCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ProjectCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ProjectCreatorHelper.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java
Fixes https://github.com/mobie/mobie-viewer-fiji/issues/583 and https://github.com/mobie/mobie-viewer-fiji/issues/611
Main changes:
- Enforces a project voxel unit (determined by the first image added)
- All images added after are checked against this (using udunits, so it can handle e.g. microns, um, micrometer etc being the same thing). Any images with units that don't match are rejected, and can't be added.
- makes project creator remember the last selected uiSelectionGroup
Requires this PR first: https://github.com/mobie/mobie-io/pull/84
> Enforce a particular unit for the project

- pom.xml
- src/main/java/org/embl/mobie/viewer/projectcreator/DatasetJsonCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/DatasetsCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ImagesCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java
- src/test/java/org/embl/mobie/viewer/projectcreator/DatasetsCreatorTest.java
- src/test/java/org/embl/mobie/viewer/projectcreator/ImagesCreatorTest.java
- src/test/java/org/embl/mobie/viewer/projectcreator/ProjectCreatorTestHelper.java
- src/test/java/org/embl/mobie/viewer/projectcreator/RemoteMetadataCreatorTest.java
fixes https://github.com/mobie/mobie-viewer-fiji/issues/623
Main changes:
- Dialog for creating dataset now has checkbox for 2D/3D
- When adding a 3D image to a 2D dataset, a dialog appears allowing you to change the dataset to 3D or abort
- adds tests for adding 2D images to 3D and 2D datasets
> Allow selection of 2D/3D when dataset is created

- pom.xml
- src/main/java/org/embl/mobie/viewer/MoBIEUtils.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ProjectCreatorHelper.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java
- src/main/java/org/embl/mobie/viewer/table/TableViewer.java
- src/main/java/org/embl/mobie/viewer/ui/UserInterfaceHelpers.java
- src/main/java/org/embl/mobie/viewer/view/additionalviews/AdditionalViewsLoader.java
- src/main/java/org/embl/mobie/viewer/view/saving/ViewsSaver.java
fixes https://github.com/mobie/mobie-viewer-fiji/issues/639 and https://github.com/mobie/mobie-viewer-fiji/issues/633
- refactors use of JFileChooser to always use the workaround from @tischi (I had to add ```new Thread()``` in a few more places to stop the file choosers hanging on windows)
- changes to SNAPSHOT version
- moves clear button down below location (while I was working on the file choosers, I found a bug where loading/saving views leads to multiple copies of the clear button - so I thought I'd just go ahead and move it)
> Refactor file chooser and move clear button

- pom.xml
- src/main/java/org/embl/mobie/viewer/display/AnnotatedRegionDisplay.java
- src/main/java/org/embl/mobie/viewer/display/SegmentationSourceDisplay.java
- src/test/java/org/embl/mobie/viewer/serialize/DatasetJsonParserTest.java
fixes https://github.com/mobie/mobie-viewer-fiji/issues/672
- saves selectedSegmentIds as int
- doesn't serialise null valueLimits
- Adds a test to open a view from the platybrowser, save it, and verify this against the dataset json schema
> make views match json schema

- src/main/java/org/embl/mobie/viewer/bdv/view/AnnotatedRegionSliceView.java
- src/main/java/org/embl/mobie/viewer/bdv/view/ImageSliceView.java
- src/main/java/org/embl/mobie/viewer/display/AnnotatedRegionDisplay.java
- src/main/java/org/embl/mobie/viewer/display/AnnotatedSourceDisplay.java
- src/main/java/org/embl/mobie/viewer/display/ImageSourceDisplay.java
- src/main/java/org/embl/mobie/viewer/display/SegmentationSourceDisplay.java
- src/main/java/org/embl/mobie/viewer/serialize/SourceTransformerListAdapter.java
- src/main/java/org/embl/mobie/viewer/view/ViewManager.java
- src/main/java/org/embl/mobie/viewer/volume/ImageVolumeViewer.java
Fixes https://github.com/mobie/mobie-viewer-fiji/issues/712 
While I was at it,  I noticed there were a few other parts that weren't being saved properly to views, so I fixed them too.
Main changes:
- Fix saving views containing merged grids
- saves displaying images in 3D / their resolution to views
- saves whether a source is visible in the slice viewer to views
- Fixes saving opacity of sourceAnnotationDisplay
> Saving merged grid view

- src/main/java/org/embl/mobie/viewer/MoBIE.java
Fixes #805 and simplifies the checks for invalid storage types in general
> Fix opening of file system projects without bdv.n5

- src/main/java/org/embl/mobie/viewer/serialize/DataSourceMapAdapter.java
- src/test/java/org/embl/mobie/viewer/create/DatasetsCreatorTest.java
- src/test/java/org/embl/mobie/viewer/create/ImagesCreatorTest.java
- src/test/java/org/embl/mobie/viewer/create/ProjectCreatorTestHelper.java
- src/test/java/org/embl/mobie/viewer/create/RemoteMetadataCreatorTest.java
Fixes https://github.com/mobie/mobie-viewer-fiji/issues/830
- implemented ```JsonSerializer``` for ```DataSourceMapAdapter```
- renamed project creator test folders to match new mobie structure
> fix dataset creator errors

- src/main/java/org/embl/mobie/lib/create/DatasetJsonCreator.java
- src/main/java/org/embl/mobie/lib/create/DatasetsCreator.java
- src/main/java/org/embl/mobie/lib/create/ImagesCreator.java
- src/main/java/org/embl/mobie/lib/create/ProjectCreator.java
- src/main/java/org/embl/mobie/lib/create/ProjectCreatorHelper.java
- src/main/java/org/embl/mobie/lib/create/ProjectJsonCreator.java
- src/main/java/org/embl/mobie/lib/create/RemoteMetadataCreator.java
- src/main/java/org/embl/mobie/lib/create/ui/ManualExportPanel.java
- src/main/java/org/embl/mobie/lib/create/ui/ProjectsCreatorPanel.java
- src/main/java/org/embl/mobie/lib/ui/SwingHelper.java
Fixes https://github.com/mobie/mobie-viewer-fiji/issues/1051
Main changes are in ```ProjectsCreatorPanel.java``` - rest are just documentation updates:
- Removes hardcoded widths/heights of labels/buttons/comboboxes
- Switches to use GridBagLayout to ensure ui components stay aligned
- Updates Javadoc throughout project creator (previously some public classes were documented and some not)
Note: if this does solve the issue for high dpi screens, then similar fixes would be needed for the main MoBIE UI etc that also show these issues
> Fix display of project creator ui on high dpi screens

- src/main/java/org/embl/mobie/MoBIESettings.java
- src/main/java/org/embl/mobie/lib/SourcesFromTableCreator.java
- src/main/java/org/embl/mobie/lib/color/ColoringModels.java
- src/main/java/org/embl/mobie/lib/color/NumericColoringModelContrastDialog.java
- src/main/java/org/embl/mobie/lib/color/lut/LUTs.java
- src/main/java/org/embl/mobie/lib/serialize/display/AbstractAnnotationDisplay.java
- src/main/java/org/embl/mobie/lib/table/saw/TableSawColumnTypes.java
- src/main/java/org/embl/mobie/lib/ui/ColumnColoringModelDialog.java
- src/main/java/org/embl/mobie/lib/view/ViewManager.java
@constantinpape @martinschorb 
Currently we are supporting these LUTs:
```
GLASBEY,
RGBA_COLUMN,
BLUE_WHITE_RED,
VIRIDIS,
```
I think the first two only work for categorial data (i.e. columns of type `String.class`), while I think the last two only work for numerical data. Is that true (sitting in a train with bad internet, thus cannot test right now)?
If it is true I think it may be better to make the color by column GUI a two stage process where
GUI 1: only select the column
GUI 2: only present **_valid_** choices for the LUTs, depending on whether or not `table.columnClass( columnName ) instanceof String`
This would avoid that users can pick invalid combinations.
What do you think?
> Improve ColorByColumn GUI

- src/main/java/org/embl/mobie/lib/hcs/HCSPattern.java
We encounter a problem with ome-zarr datasets that have more than 1 channel. With the `MoBIE -> Open -> Open HCS Dataset...` command we got only displayed the very first channel. This also was true when we opened MoBIE projects, but this is not surprising since it uses the same code.
This change fixes this issue. All channels are loaded into the HCS dataset for OmeZarr.
> Add all available channels of OMEZarr.

- pom.xml
- src/main/java/org/embl/mobie/lib/create/DatasetSerializer.java
- src/main/java/org/embl/mobie/lib/create/ImagesCreator.java
- src/main/java/org/embl/mobie/lib/create/ProjectCreator.java
- src/main/java/org/embl/mobie/lib/create/ProjectCreatorHelper.java
- src/main/java/org/embl/mobie/lib/create/RemoteMetadataCreator.java
- src/main/java/org/embl/mobie/lib/create/ui/ProjectsCreatorUI.java
- src/test/java/org/embl/mobie/lib/create/ImagesCreatorTest.java
- src/test/java/org/embl/mobie/lib/create/RemoteMetadataCreatorTest.java
- src/test/java/projects/rafael/CreateRafaelProject.java
For https://github.com/mobie/mobie-viewer-fiji/issues/1116
This PR:
- Fixes linking images within the project creator (uses absolutePath if the image is outside the project directory)
- Fixes remote metadata creation
- Fixes failing project creator tests + adds more for linking / remote metadata
- Updates the javadoc
Note: I've currently commented out the line in `ImagesCreatorTest` that validates the dataset json against the schema. This is due to the missing `absolutePath`. It can be un-commented once this is added.
Also, this doesn't currently support directly giving an `s3address` to the project creator (for files that are already stored remotely). This is probably best added later, as it's a new feature that wasn't in the original project creator.
> Fix linking

- src/main/java/org/embl/mobie/lib/data/ImageGridSources.java
- Fixed the logic for resolving paths by using the root directory when it's not null.
- If the root directory is null, the path is now resolved using the Cellprofiler column.
> fix: correct path resolution with root directory handling

- src/main/java/org/embl/mobie/lib/bdv/view/SliceViewer.java
- src/main/java/org/embl/mobie/lib/create/ProjectCreatorHelper.java
- src/main/java/org/embl/mobie/lib/view/ViewManager.java
- src/main/java/org/embl/mobie/lib/view/delete/ViewDeleter.java
- src/main/java/org/embl/mobie/lib/view/save/SelectExistingViewDialog.java
- src/main/java/org/embl/mobie/ui/UserInterface.java
- src/main/java/org/embl/mobie/ui/UserInterfaceHelper.java
For https://github.com/mobie/mobie-viewer-fiji/issues/1148
This PR allows deletion of views via right clicking in the MoBIE viewer and selecting `Delete View`. Similar to the view saving options, it allows deleting views from the 'current project' (i.e. the dataset.json) or an 'external file' (any view .json saved on the file system). The 'current project' option is currently only implemented for local projects - if you try to use it with a github / s3 project it should throw an error.
Let me know if any changes are needed! I tried it out locally with a few example projects, but it would be great if more people could test this out to check everything is working correctly :smile:
> Allow deletion of views via the UI

- src/main/java/org/embl/mobie/lib/create/ImagesCreator.java
For https://github.com/mobie/mobie-viewer-fiji/issues/1218
This should fix the reported `NullPointerException` + means all the project creator tests now pass. There is still a long deprecation warning printed out (see below), but this doesn't seem to stop anything working correctly.  As far as I can tell this is to do with [the `AmazonS3ClientBuilder.standard();` line in MoBIE](https://github.com/mobie/mobie-viewer-fiji/blob/main/src/main/java/org/embl/mobie/MoBIE.java#L94), rather than the project creator code itself.
```
15:43:38.782 [Thread-21] WARN com.amazonaws.util.VersionInfoUtils - The AWS SDK for Java 1.x entered maintenance mode starting July 31, 2024 and will reach end of support on December 31, 2025. For more information, see …
```
> Fix null pointer exception in ImageCreator
