- src/main/java/de/embl/cba/mobie/bookmark/BookmarksJsonParser.java
- src/main/java/de/embl/cba/mobie/bookmark/BookmarksManager.java
Match to changes in imagej-utils - uses enum for file location.
For https://github.com/mobie/mobie-viewer-fiji/issues/135
> Switch to enum for file location

- src/main/java/de/embl/cba/mobie/bookmark/BookmarksJsonParser.java
- src/main/java/de/embl/cba/mobie/dataset/DatasetsParser.java
- src/main/java/de/embl/cba/mobie/image/ImagePropertiesEditor.java
- src/main/java/de/embl/cba/mobie/image/ImagesJsonParser.java
- src/main/java/de/embl/cba/mobie/projects/ProjectsCreator.java
- src/main/java/de/embl/cba/mobie/projects/ProjectsCreatorPanel.java
- src/main/java/de/embl/cba/mobie/ui/command/AddCurrentImageToProject.java
- src/main/java/de/embl/cba/mobie/ui/command/CreateNewMoBIEProjectCommand.java
- src/main/java/de/embl/cba/mobie/ui/command/EditMoBIEProjectCommand.java
- src/main/java/de/embl/cba/mobie/ui/viewer/ActionPanel.java
- src/main/java/de/embl/cba/mobie/utils/JsonUtils.java
- src/main/java/de/embl/cba/mobie/utils/ui/SwingUtils.java
Making local mobie projects via the UI - currently doesn't deal with anything remote, just file system!
Main changes:
- New command 'Create new MoBIE Project...', allows you to choose a file location for a project, and then edit it
- New command 'Edit MoBIE Project...', allows you to create datasets, rename datasets, select the default dataset, edit image properties (i.e. all the image.json parameters), edit which images are shown in the default bookmark
-At the moment, images are added via a separate command (in future this should also be a button in the 'edit mobie project...' window!) - 'Add Current Image to MoBiE project'. This grabs the currently open image in fiji, converts it to bdv-n5/bdv-h5, creates the default table for segmentations, updates all the json files..
> Project from UI

- src/main/java/de/embl/cba/mobie/projects/ProjectsCreator.java
- src/main/java/de/embl/cba/mobie/projects/ProjectsCreatorPanel.java
Replaces spaces in all input with _
> replace spaces in names

- src/main/java/de/embl/cba/mobie/projects/ProjectsCreator.java
- src/main/java/de/embl/cba/mobie/projects/ProjectsCreatorPanel.java
Adds a field for an affine transform to the 'add current image' dialog for mobie project creator.
> Affine support

- src/main/java/de/embl/cba/mobie/projects/ProjectsCreator.java
- src/main/java/de/embl/cba/mobie/projects/ProjectsCreatorPanel.java
Adds manual specification of n5/h5 parameters like downsampling and chunking.
@tischi  Could you merge this and put it on the main MoBIE site? I need it for tomorrow. Thanks!
> Manual settings for h5 / n5 export

- pom.xml
- src/main/java/de/embl/cba/mobie/bookmark/Bookmark.java
- src/main/java/de/embl/cba/mobie/bookmark/BookmarksManager.java
- src/main/java/de/embl/cba/mobie/image/ImagePropertiesToMetadataAdapter.java
- src/main/java/de/embl/cba/mobie/image/MutableImageProperties.java
- src/main/java/de/embl/cba/mobie/ui/viewer/ActionPanel.java
- src/main/java/de/embl/cba/mobie/ui/viewer/SourcesPanel.java
- src/test/java/develop/DevelopInverseTransform.java
- src/test/java/develop/DevelopManualTransformCapture.java
- src/test/java/run/RunImageJ.java
- src/test/java/run/RunOpenCustomBrowserCommand.java
- src/test/java/run/RunOpenPlatyBrowserCommand.java
- src/test/java/users/sultan/ViewNeuropils.java
@K-Meech I started working on it; I will let you know once it is done.
> Add sourceTransform to Bookmark and MutableImageProperties

- src/main/java/de/embl/cba/mobie2/color/MoBIEColoringModel.java
- src/main/java/de/embl/cba/mobie2/display/ImageDisplay.java
- src/main/java/de/embl/cba/mobie2/display/SegmentationDisplay.java
- src/main/java/de/embl/cba/mobie2/plot/ScatterPlotViewer.java
- src/main/java/de/embl/cba/mobie2/table/TableViewer.java
- src/main/java/de/embl/cba/mobie2/volume/SegmentsVolumeView.java
Makes serialisable copes of imageDisplay and segmentationDisplay
@tischi I wasn't sure where to fetch ```showImagesIn3d``` for the imageDisplay. Showing images in 3D isn't supported in the viewer yet, so I'm not sure where this info will be.
> make copies of imageDisplay and segmentationDisplay

- src/main/java/de/embl/cba/mobie/projectcreator/ImagesCreator.java
Fix for issue: https://github.com/mobie/mobie-viewer-fiji/issues/251
> fix for moving image

- src/main/java/de/embl/cba/mobie/MoBIE.java
- src/main/java/de/embl/cba/mobie/Utils.java
- src/main/java/de/embl/cba/mobie/grid/DefaultAnnotatedIntervalTableRow.java
- src/main/java/de/embl/cba/mobie/grid/GridOverlaySourceDisplay.java
- src/main/java/de/embl/cba/mobie/projectcreator/DatasetJsonCreator.java
- src/main/java/de/embl/cba/mobie/projectcreator/DatasetsCreator.java
- src/main/java/de/embl/cba/mobie/projectcreator/ImagesCreator.java
- src/main/java/de/embl/cba/mobie/projectcreator/ProjectCreatorHelper.java
- src/main/java/de/embl/cba/mobie/projectcreator/RemoteMetadataCreator.java
- src/main/java/de/embl/cba/mobie/table/TableViewer.java
- src/main/java/de/embl/cba/mobie/ui/SwingHelper.java
- src/main/java/de/embl/cba/mobie/ui/UserInterfaceHelper.java
- src/main/java/de/embl/cba/mobie/view/ViewerManager.java
- src/main/java/de/embl/cba/mobie/view/additionalviews/AdditionalViewsLoader.java
- src/main/java/de/embl/cba/mobie/view/saving/ViewSavingHelpers.java
- src/main/java/de/embl/cba/mobie/view/saving/ViewsSaver.java
- src/test/java/projects/OpenLocalCropTest.java
- src/test/java/projects/OpenLocalTestData.java
- src/test/java/projects/OpenRemoteZebrafish.java
@tischi  Are you happy to merge this?
I made a few last changes (main ones in this commit: https://github.com/mobie/mobie-viewer-fiji/commit/7dfc1ad9c82bb0a1c30b6c82c1a4c8bdfaa1daf3 )
> Load columns

- src/main/java/de/embl/cba/mobie/display/SegmentationSourceDisplay.java
- src/main/java/de/embl/cba/mobie/plot/ScatterPlotViewer.java
- src/main/java/de/embl/cba/mobie/view/ViewerManager.java
Fixes some issues with bookmark loading / saving:
- fixes saving opacity values for segmentations in bookmarks
- fixes tables in saved bookmarks to include the default
- fixes loading scatter plot settings from bookmarks
> Bookmark saving

- pom.xml
- src/main/java/de/embl/cba/mobie/MoBIE.java
- src/main/java/de/embl/cba/mobie/bdv/ImageSliceView.java
- src/main/java/de/embl/cba/mobie/bdv/SegmentationImageSliceView.java
- src/main/java/de/embl/cba/mobie/view/ViewerManager.java
- src/test/java/projects/OpenRemotePlatynereis.java
@K-Meech 
Thank you for investigating the memory leaks.
Here is some code to get you started on testing whether closing the ImgLoader helps.
> Seal memory leaks

- pom.xml
- src/main/java/de/embl/cba/mobie/bdv/ImageSliceView.java
- src/main/java/de/embl/cba/mobie/bdv/ScreenShotMaker.java
- src/main/java/de/embl/cba/mobie/bdv/SegmentationImageSliceView.java
- src/main/java/de/embl/cba/mobie/bdv/SliceViewer.java
- src/main/java/de/embl/cba/mobie/bdv/SourcesAtMousePositionSupplier.java
- src/main/java/de/embl/cba/mobie/color/MoBIEColoringModel.java
- src/main/java/de/embl/cba/mobie/color/SelectedSegmentsColorConfiguratorCommand.java
- src/main/java/de/embl/cba/mobie/color/opacity/AdjustableOpacityColorConverter.java
- src/main/java/de/embl/cba/mobie/color/opacity/VolatileAdjustableOpacityColorConverter.java
- src/main/java/de/embl/cba/mobie/command/ScreenShotMakerCommand.java
- src/main/java/de/embl/cba/mobie/display/ImageSourceDisplay.java
- src/main/java/de/embl/cba/mobie/grid/GridOverlaySourceDisplay.java
- src/main/java/de/embl/cba/mobie/playground/PlaygroundHelpers.java
- src/main/java/de/embl/cba/mobie/table/TableViewer.java
- src/main/java/de/embl/cba/mobie/transform/CroppedSource.java
- src/main/java/de/embl/cba/mobie/transform/TransformerHelper.java
- src/main/java/de/embl/cba/mobie/ui/UserInterfaceHelper.java
- src/test/java/projects/OpenRemoteYeastCLEM.java
I am not sure yet whether everything is working in this branch because I still need to add blending modes to the yeast CLEM project dataset.json.
But it also contains the new `SelectedSegmentsColorConfiguratorCommand`. So, if you urgently need this, you could run from this branch (bad practice from my side by the way, I should have added above command to a new branch...).
> Blending modes

- src/main/java/de/embl/cba/mobie/table/TableViewer.java
Allows selection of segments based on the values in a chosen column
- equal to some value ( for categorical and numeric columns )
- less than/greater than some value ( for numeric columns )
> Select by column values

- src/main/java/de/embl/cba/mobie/annotate/Annotator.java
- src/main/java/de/embl/cba/mobie/command/AddRemoteToMoBIEProjectCommand.java
- src/main/java/de/embl/cba/mobie/command/CreateNewMoBIEProjectCommand.java
- src/main/java/de/embl/cba/mobie/command/EditMoBIEProjectCommand.java
- src/main/java/de/embl/cba/mobie/projectcreator/ui/ProjectsCreatorPanel.java
- src/main/java/de/embl/cba/mobie/ui/UserInterface.java
- src/main/java/de/embl/cba/mobie/view/ViewerManager.java
- src/main/java/de/embl/cba/mobie/view/additionalviews/AdditionalViewsLoader.java
- src/main/java/de/embl/cba/mobie/view/saving/SelectExistingViewFrame.java
Fixes https://github.com/mobie/mobie-viewer-fiji/issues/341, https://github.com/mobie/mobie-viewer-fiji/issues/314, https://github.com/mobie/mobie-viewer-fiji/issues/288 and https://github.com/mobie/mobie-viewer-fiji/issues/353
@tischi - could you check this fixes the display issues on mac? (all the changes are in the 'laf' branch on this repo)
Could you check:
- changing to a different dataset (https://github.com/mobie/mobie-viewer-fiji/issues/288)
- loading an additional view that adds a new ui selection group (https://github.com/mobie/mobie-viewer-fiji/issues/341)
- the project creator dropdown (https://github.com/mobie/mobie-viewer-fiji/issues/314)
- the annotation dialog, when you add multiple categories (https://github.com/mobie/mobie-viewer-fiji/issues/353)
> fix laf issues

- src/main/java/de/embl/cba/mobie/n5/openorganelle/OpenOrganelleN5ImageLoader.java
@constantinpape, check the image, please, when you have time.
It should be possible to open images through BDV and  MoBIE.
> Fix open organelle boundary chunks reading

- src/main/java/org/embl/mobie/viewer/bdv/view/SliceViewer.java
- src/main/java/org/embl/mobie/viewer/command/CreateNewMoBIEProjectCommand.java
- src/main/java/org/embl/mobie/viewer/command/NonSelectedSegmentsOpacityAdjusterCommand.java
- src/main/java/org/embl/mobie/viewer/command/OpenOMEZARRCommand.java
- src/main/java/org/embl/mobie/viewer/command/OpenOMEZARRFromS3AdvancedCommand.java
- src/main/java/org/embl/mobie/viewer/command/OpenOMEZARRFromS3Command.java
- src/main/java/org/embl/mobie/viewer/command/RandomColorSeedChangerCommand.java
- src/main/java/org/embl/mobie/viewer/command/SegmentsVolumeRenderingConfiguratorCommand.java
- src/main/java/org/embl/mobie/viewer/command/SelectedSegmentsColorConfiguratorCommand.java
- src/main/java/org/embl/mobie/viewer/command/SourceAndConverterBlendingModeChangerCommand.java
- src/main/java/org/embl/mobie/viewer/command/WriteOMEZARRCommand.java
- src/test/java/commands/OpenOMEZARRCommand.java
- src/test/java/commands/OpenOMEZARRFromS3AdvancedCommand.java
- src/test/java/commands/OpenOMEZARRFromS3Command.java
- Change naming according to https://github.com/mobie/mobie-viewer-fiji/issues/437
- Clean main methods for OmeZarr commands
> Change commands naming

- src/main/java/org/embl/mobie/viewer/transform/MergedGridSourceTransformer.java
Closes https://github.com/mobie/mobie-viewer-fiji/issues/483
> add transient for mergedGridSource

- src/main/java/org/embl/mobie/viewer/MoBIE.java
- src/main/java/org/embl/mobie/viewer/transform/MergedGridSourceTransformer.java
- src/main/java/org/embl/mobie/viewer/view/ViewManager.java
- src/test/java/projects/OpenLocalCovidPlate.java
@K-Meech 
Could we merge this?
I should fix https://github.com/mobie/mobie-viewer-fiji/issues/511
That is, it should open this without an error:
```
final ImageJ imageJ = new ImageJ();
imageJ.ui().showUI();
try {
new MoBIE("/g/kreshuk/pape/Work/mobie/covid-if-project/data",
MoBIESettings.settings().imageDataFormat( ImageDataFormat.OmeZarr ) );
} catch (IOException e) {
e.printStackTrace();
}
```
> Fixes #511

- src/main/java/org/embl/mobie/viewer/MoBIE.java
- src/main/java/org/embl/mobie/viewer/display/ImageSourceDisplay.java
- src/main/java/org/embl/mobie/viewer/ui/UserInterfaceHelper.java
- src/main/java/org/embl/mobie/viewer/view/ViewManager.java
- src/main/java/org/embl/mobie/viewer/volume/ImageVolumeViewer.java
- src/main/java/org/embl/mobie/viewer/volume/SegmentsVolumeViewer.java
Really just a draft for now...
> Volumetric image view

- src/main/java/org/embl/mobie/viewer/serialize/ViewerTransformAdapter.java
- src/main/java/org/embl/mobie/viewer/transform/MoBIEViewerTransformChanger.java
- src/main/java/org/embl/mobie/viewer/transform/NormalVectorViewerTransform.java
- src/main/java/org/embl/mobie/viewer/transform/NormalizedAffineViewerTransform.java
- src/main/java/org/embl/mobie/viewer/transform/PositionViewerTransform.java
- src/main/java/org/embl/mobie/viewer/transform/TimepointViewerTransform.java
- src/main/java/org/embl/mobie/viewer/transform/ViewerTransform.java
- src/main/java/org/embl/mobie/viewer/ui/UserInterfaceHelper.java
- src/test/java/projects/OpenRemotePlatynereisBranch.java
Not yet ready, but you could have a look already, if you like...
> Draft: NormalVectorViewerTransform

- src/main/java/org/embl/mobie/viewer/display/AbstractSourceDisplay.java
- src/main/java/org/embl/mobie/viewer/table/TableViewer.java
- src/main/java/org/embl/mobie/viewer/ui/UserInterfaceHelper.java
- src/main/java/org/embl/mobie/viewer/view/ViewManager.java
- src/test/java/projects/OpenRemoteCovidScreen.java
Now against the correct branch.
> Fixes #540

- src/main/java/org/embl/mobie/viewer/MoBIE.java
- src/main/java/org/embl/mobie/viewer/SourceNameEncoder.java
- src/main/java/org/embl/mobie/viewer/bdv/view/SegmentationSliceView.java
- src/main/java/org/embl/mobie/viewer/bdv/view/SliceViewer.java
- src/main/java/org/embl/mobie/viewer/color/LabelConverter.java
- src/main/java/org/embl/mobie/viewer/segment/BdvSegmentSelector.java
- src/main/java/org/embl/mobie/viewer/segment/SegmentAdapter.java
- src/main/java/org/embl/mobie/viewer/transform/MergedGridSource.java
- src/main/java/org/embl/mobie/viewer/transform/MergedGridSourceTransformer.java
- src/main/java/org/embl/mobie/viewer/view/ViewManager.java
- src/test/java/develop/DevelopSourceNameBitEncoding.java
- src/test/java/projects/OpenRemoteCovidScreen.java
@K-Meech
Could you have a look whether the code looks OK?
And, only if you have time, whether it really fixes #541?
For me, it does.
> Fixes #541

- src/main/java/org/embl/mobie/viewer/bdv/ScreenShotMaker.java
- src/main/java/org/embl/mobie/viewer/bdv/ViewerTransformLogger.java
- src/main/java/org/embl/mobie/viewer/playground/ScreenShotMakerCommand.java
Fixes #555 and adds logging of normal vector viewer transform, which can be used to go "level" the view of the Platy.
> Fixes #555

- src/test/resources/prospr-myosin-n5.xml
- src/test/resources/prospr-myosin-zarr.xml
@tischi this was the only thing I could find still having the `Authentication` tag.
> Remove Authentication field from test data

- src/main/java/org/embl/mobie/viewer/command/OpenMoBIEProjectWithS3CredentialsCommand.java
- src/main/java/org/embl/mobie/viewer/command/OpenOMEZARRCommand.java
- src/main/java/org/embl/mobie/viewer/command/OpenOMEZARRFromS3Command.java
- src/main/java/org/embl/mobie/viewer/command/OpenOMEZARRFromS3WithCredentialsCommand.java
- src/test/java/demo/DemoOpenOMEZARRFromS3WithCredentialsCommand.java
> S3credentials

- src/main/java/org/embl/mobie/viewer/projectcreator/DatasetJsonCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ImagesCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java
- src/test/java/org/embl/mobie/viewer/projectcreator/ImagesCreatorTest.java
- src/test/java/org/embl/mobie/viewer/projectcreator/RemoteMetadataCreatorTest.java
Main changes:
- suggests name from image title (fixes https://github.com/mobie/mobie-viewer-fiji/issues/585)
- adds option to make view exclusive (fixes https://github.com/mobie/mobie-viewer-fiji/issues/571)
- removes option to not make a view (for https://github.com/mobie/mobie-viewer-fiji/issues/579)
> Project creator fixes

- src/main/java/org/embl/mobie/viewer/MoBIE.java
- src/main/java/org/embl/mobie/viewer/MoBIEUtils.java
- src/main/java/org/embl/mobie/viewer/bdv/view/SliceViewer.java
- src/main/java/org/embl/mobie/viewer/command/BigWarpRegistrationCommand.java
- src/main/java/org/embl/mobie/viewer/command/ImagePlusExportCommand.java
- src/main/java/org/embl/mobie/viewer/command/ManualRegistrationCommand.java
- src/main/java/org/embl/mobie/viewer/playground/BdvPlaygroundUtils.java
- src/test/java/projects/OpenRemoteCLEMExample.java
WIP on exporting sources to imageJ1...
> Add ImagePlusExportCommand

- src/main/java/org/embl/mobie/viewer/MoBIE.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java
fixes https://github.com/mobie/mobie-viewer-fiji/issues/570
> Make project creator remember last choices

- src/main/java/org/embl/mobie/viewer/projectcreator/ImagesCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java
fixes https://github.com/mobie/mobie-viewer-fiji/issues/586
I add a message in two places - so that it outputs whether you use it through the ui, or directly via the api.
> add message for multi-channel images

- src/main/java/org/embl/mobie/viewer/command/WriteOMEZARRCommand.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ImagesCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ProjectCreatorHelper.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java
- src/test/java/org/embl/mobie/viewer/projectcreator/ImagesCreatorTest.java
- src/test/java/org/embl/mobie/viewer/projectcreator/RemoteMetadataCreatorTest.java
Needs https://github.com/mobie/mobie-io/pull/69 first
- Removes bdv ome-zarr from project creator
- Adds v0.4 ome-zarr to project creator + ome-zarr export command
> V4 ome zarr

- src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java
Very minor fix for the project creator. I'll just go ahead and merge this, once the tests finish :)
> add missing break

- src/main/java/org/embl/mobie/viewer/view/saving/SelectExistingViewDialog.java
- src/main/java/org/embl/mobie/viewer/view/saving/ViewsSaver.java
fixes https://github.com/mobie/mobie-viewer-fiji/issues/606
When a new view is saved, it also adds it to the dropdown menus in MoBIE
> add newly saved views to ui

- pom.xml
- src/main/java/org/embl/mobie/viewer/bdv/view/SliceViewer.java
- src/main/java/org/embl/mobie/viewer/command/OpenMoBIEProjectWithS3CredentialsCommand.java
- src/main/java/org/embl/mobie/viewer/serialize/DatasetJsonParser.java
- src/main/java/org/embl/mobie/viewer/view/saving/ViewSavingHelpers.java
- src/main/java/org/embl/mobie/viewer/view/saving/ViewsSaver.java
Needs https://github.com/mobie/mobie-io/pull/81
@K-Meech Could you please have a look at the changes I made to the `DatasetJsonParser`. Is that too naive? Looks somehow to easy to be true...
> Write views s3

- src/main/java/org/embl/mobie/viewer/view/saving/ViewsSaver.java
Hi @K-Meech,
I think in fact for now I only need to be able to save the view to the project.
So this would suffice.
Looks OK for you?
> Fixes #617: Refactor to enable view saving to project via API

- src/main/java/org/embl/mobie/viewer/projectcreator/DatasetsCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ImagesCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/ProjectCreator.java
- src/main/java/org/embl/mobie/viewer/projectcreator/RemoteMetadataCreator.java
For https://github.com/mobie/mobie-viewer-fiji/issues/591
Add javadoc for main project creator api functions
(I'll also update the mobie.github.io soon to give more examples)
> project creator api javadoc

- src/main/java/org/embl/mobie/viewer/display/AnnotatedRegionDisplay.java
- src/main/java/org/embl/mobie/viewer/display/SegmentationSourceDisplay.java
- src/test/java/org/embl/mobie/viewer/serialize/DatasetJsonParserTest.java
Fixes https://github.com/mobie/mobie-viewer-fiji/issues/701
I'll go ahead and merge this once the tests complete.
> remove BlendingMode from saved segmentation view

- src/main/java/org/embl/mobie/viewer/projectcreator/ProjectCreatorHelper.java
I'll go ahead and merge this when the tests finish - it's a very minor fix to the project creator
> allow negative values in project creator affine

- src/main/java/org/embl/mobie/viewer/project/PublishedFigures.java
Hey @tischi,
I realized that we didn't update the views for the new version of the submission yet. I did this now in the projects, this PR syncs the MoBIE open view menu with it.
Could you please merge this and then create a new MoBIE main release with the changes?
I will also update the bioRxiv submission so that it matches this.
> Update views for the paper figures

- src/main/java/org/embl/mobie/viewer/create/ui/ProjectsCreatorPanel.java
Fixes a minor issue with the project creator ui comboboxes
> Fix view combobox not updating when new dataset created

- src/main/java/org/embl/mobie/viewer/published/PublishedFigures.java
- src/main/java/org/embl/mobie/viewer/published/PublishedProjects.java
Updating published projects and views
> Updates for revision

- MOBIE-BETA.md
too annoying to type it from the screenshot - also error prone due to it being case sensitive
> make update site URL copy-pastable

- src/main/java/org/embl/mobie/lib/ui/UserInterfaceHelper.java
I added some tooltips to the tiny buttons in the UI that should help users to make a _little_ more sense of their function.
If you have any better ideas for tooltips I'm happy to modify them!
Cheers
> added tooltips to some of the user interface

- src/main/java/org/embl/mobie/lib/bdv/ImageNameOverlay.java
- src/main/java/org/embl/mobie/lib/files/FileSourcesDataSetter.java
- src/main/java/org/embl/mobie/lib/files/ImageFileSources.java
see https://github.com/mobie/mobie-viewer-fiji/issues/1013
> Issue1013: overlay names is a mess for multiple images on top of each other

- src/main/java/org/embl/mobie/lib/create/ImagesCreator.java
- src/test/java/org/embl/mobie/lib/create/ImagesCreatorTest.java
For https://github.com/mobie/mobie-viewer-fiji/issues/1133
> add further log statements for added images

- src/test/java/org/embl/mobie/lib/create/ImagesCreatorTest.java
> Fix "Found incompatible ImageJ class" exception
